name: CI

on:
  merge_group:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
  push:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # v4.1.4
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm install
      - run: pnpm typecheck
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm install
      - run: pnpm run lint
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm install
      - run: pnpm run format:ci
  test:
    runs-on: ubuntu-22.04
    needs: [lint, typecheck, format]
    strategy:
      matrix:
        node: ["20"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm install
      - run: pnpm run test:unit:coverage
      - uses: codecov/codecov-action@v4.5.0
        with:
          # files: packages/**/coverage/cobertura-coverage.xmls
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  # accessibility:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: '0'
  #     - uses: pnpm/action-setup@v3.0.0
  #     - name: Use Node.js
  #       uses: actions/setup-node@v4.0.2
  #       with:
  #         node-version: 20
  #         cache: 'pnpm'
  #     - run: pnpm install
  #     - run: pnpm run build
  #     - run: pnpm install
  #     - run: pnpm run test:a11y
  build:
    strategy:
      matrix:
        node: ["20"]
    runs-on: ubuntu-22.04
    needs: [lint, typecheck, format]
    steps:
      - uses: actions/checkout@v4 # v4.1.4
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm run build
  build-examples: # This will build all projects in the examples folder, it assures that all examples are working
    strategy:
      matrix:
        node: ["20"]
    runs-on: ubuntu-22.04
    needs: [lint, test, format]
    steps:
      - uses: actions/checkout@v4 # v4.1.4
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm build
      - run: pnpm install
      - run: pnpm run build:examples
