name: CI

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.5
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-
    - name: Use Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 16
    - run: yarn
    - run: yarn run lint
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '14', '16' ]
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: "0"
    - uses: actions/cache@v2.1.5
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-
    - name: Use Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node }}
    - run: yarn
    - run: yarn run test:coverage
    - uses: codecov/codecov-action@v1.5.0
  build:
    strategy:
      matrix:
        node: [ '14', '16' ]
    runs-on: ubuntu-20.04
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Use Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node }}
    - run: yarn --pure-lockfile
    - run: yarn run build
  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    if: github.ref == 'refs/heads/master'
    env:
      GIT_COMMITTER_NAME: Scaleway Bot
      GIT_COMMITTER_EMAIL: github@scaleway.com
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: "0"
        persist-credentials: false
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Use Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 16
    - run: yarn --pure-lockfile
    - run: yarn run build
    - run: yarn run semantic-release
      env:
        HUSKY: 0
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
