name: CI

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
  push:
    branches:
      - main

jobs:
<<<<<<< HEAD
  typecheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn
      - run: yarn run build
      - run: yarn run tsc --noEmit || true
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn
      - run: yarn run lint
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ["17"]
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: "0"
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - run: yarn
      - run: yarn run test:unit:coverage
      - uses: codecov/codecov-action@v2.1.0
  accessibility:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: "0"
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn
      - run: yarn run test:a11y
=======
  # typecheck:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: 17
  #         cache: "yarn"
  #     - run: yarn
  #     - run: yarn run build
  #     - run: yarn run tsc --noEmit || true
  # lint:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: 17
  #         cache: "yarn"
  #     - run: yarn
  #     - run: yarn run lint
  # test:
  #   runs-on: ubuntu-20.04
  #   strategy:
  #     matrix:
  #       node: ["17"]
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #       with:
  #         fetch-depth: "0"
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: ${{ matrix.node }}
  #         cache: "yarn"
  #     - run: yarn
  #     - run: yarn run test:unit:coverage
  #     - uses: codecov/codecov-action@v2.1.0
  # accessibility:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #       with:
  #         fetch-depth: "0"
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: 17
  #         cache: "yarn"
  #     - run: yarn
  #     - run: yarn run test:a11y
>>>>>>> fix: ci action
  build:
    strategy:
      matrix:
        node: ["17"]
    runs-on: ubuntu-20.04
    # needs: [lint, test]
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn run build
<<<<<<< HEAD
<<<<<<< HEAD
=======
      - name: Build Storybook
=======
      - name: Save built Storybook
>>>>>>> fix: ci action
        uses: actions/upload-artifact@v2
        with:
          name: storybook-static
          path: ./dist
          retention-days: 2
  visual:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17
          cache: "yarn"
      - name: Download built Storybook
        uses: actions/download-artifact@v2
        with:
          name: storybook-static
          path: storybook-static
      - run: yarn install
<<<<<<< HEAD
<<<<<<< HEAD
      - run: yarn run loki:test
>>>>>>> fix: ci action
=======
      - run: yarn run loki test
>>>>>>> fix: ci action
=======
      - run: yarn run loki:test
>>>>>>> fix: ci action
  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    if: github.ref == 'refs/heads/main'
    env:
      GIT_COMMITTER_NAME: Scaleway Bot
      GIT_COMMITTER_EMAIL: github@scaleway.com
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: "0"
          persist-credentials: false
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 17
      - run: yarn install
      - run: yarn run build
      - run: yarn run semantic-release
        env:
          HUSKY: 0
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
