name: CI

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
  push:
    branches:
      - main

jobs:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  typecheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
=======
=======
>>>>>>> fix: restore other jobs
  typecheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
<<<<<<< HEAD
>>>>>>> fix: ci action
=======
>>>>>>> fix: restore other jobs
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn
      - run: yarn run build
      - run: yarn run tsc --noEmit || true
  lint:
    runs-on: ubuntu-20.04
    steps:
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
=======
      - uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
>>>>>>> fix: ci action
=======
      - uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
>>>>>>> fix: restore other jobs
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn
      - run: yarn run lint
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
<<<<<<< HEAD
<<<<<<< HEAD
        node: ["17"]
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: "0"
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
=======
=======
>>>>>>> fix: restore other jobs
        node: ["14", "16", "17"]
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: "0"
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
<<<<<<< HEAD
>>>>>>> fix: ci action
=======
>>>>>>> fix: restore other jobs
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - run: yarn
      - run: yarn run test:unit:coverage
      - uses: codecov/codecov-action@v2.1.0
  accessibility:
    runs-on: ubuntu-20.04
    steps:
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: "0"
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
=======
=======
>>>>>>> fix: restore other jobs
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: "0"
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
<<<<<<< HEAD
>>>>>>> fix: ci action
=======
>>>>>>> fix: restore other jobs
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn
      - run: yarn run test:a11y
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> fix: ci action
  # typecheck:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: 17
  #         cache: "yarn"
  #     - run: yarn
  #     - run: yarn run build
  #     - run: yarn run tsc --noEmit || true
  # lint:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: 17
  #         cache: "yarn"
  #     - run: yarn
  #     - run: yarn run lint
  # test:
  #   runs-on: ubuntu-20.04
  #   strategy:
  #     matrix:
  #       node: ["14", "16", "17"]
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #       with:
  #         fetch-depth: "0"
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: ${{ matrix.node }}
  #         cache: "yarn"
  #     - run: yarn
  #     - run: yarn run test:unit:coverage
  #     - uses: codecov/codecov-action@v2.1.0
  # accessibility:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #       with:
  #         fetch-depth: "0"
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: 17
  #         cache: "yarn"
  #     - run: yarn
  #     - run: yarn run test:a11y
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> fix: ci action
=======
>>>>>>> fix: ci action
=======
>>>>>>> fix: ci action
=======
>>>>>>> fix: restore other jobs
  build:
    strategy:
      matrix:
        node: ["14", "16", "17"]
    runs-on: ubuntu-20.04
<<<<<<< HEAD
<<<<<<< HEAD
    # needs: [lint, test]
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
=======
=======
>>>>>>> fix: restore other jobs
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
<<<<<<< HEAD
>>>>>>> fix: ci action
=======
>>>>>>> fix: restore other jobs
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn run build
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
      - name: Build Storybook
=======
      - name: Save built Storybook
>>>>>>> fix: ci action
        uses: actions/upload-artifact@v2
        with:
          name: storybook-static
          path: ./dist
          retention-days: 2
=======
=======
>>>>>>> fix: ci action
  # build:
  #   strategy:
  #     matrix:
  #       node: ["14", "16", "17"]
  #   runs-on: ubuntu-20.04
  #   needs: [lint, test]
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: ${{ matrix.node }}
  #     - run: yarn install
  #     - run: yarn run build
<<<<<<< HEAD
>>>>>>> fix: ci action
=======
>>>>>>> fix: ci action
=======
=======
>>>>>>> fix: ci action
  build-storybook:
=======
  build-storybook-visual:
>>>>>>> fix: restore other jobs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17
      - run: yarn install
      - run: yarn run build:storybook-visual
      - uses: actions/cache@v2
        id: restore-build-visual
        with:
          path: ./*
          key: ${{ github.sha }}
>>>>>>> fix: ci action
  visual:
    needs: [build-storybook-visual]
    strategy:
      matrix:
        filter: ["[A-C]", "D", "[E-Z]"]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn install
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
      - run: yarn run loki:test
>>>>>>> fix: ci action
=======
      - run: yarn run loki test
>>>>>>> fix: ci action
=======
=======
      - run: yarn run build:storybook
<<<<<<< HEAD
>>>>>>> fix: ci action
      - run: yarn run loki:test
>>>>>>> fix: ci action
=======
=======
      - uses: actions/cache@v2
        id: restore-build-visual
        with:
          path: ./*
          key: ${{ github.sha }}
<<<<<<< HEAD
>>>>>>> fix: ci action
      - run: yarn run loki:test --storiesFilter ^Components/${{ matrix.filter }}
<<<<<<< HEAD
>>>>>>> fix: ci action
=======
=======
      - run: yarn run visual:test --storiesFilter ^Components/${{ matrix.filter }}
>>>>>>> fix: replace ref to loki by visual
      - name: Archive screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: storybook-screenshots
          path: .loki/difference
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> fix: ci action
  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    if: github.ref == 'refs/heads/main'
    env:
      GIT_COMMITTER_NAME: Scaleway Bot
      GIT_COMMITTER_EMAIL: github@scaleway.com
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: "0"
          persist-credentials: false
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 17
      - run: yarn install
      - run: yarn run build
      - run: yarn run semantic-release
        env:
          HUSKY: 0
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
=======
=======
          retention-days: 5
<<<<<<< HEAD
>>>>>>> fix: ci action
  # deploy:
  #   runs-on: ubuntu-20.04
  #   needs: [build]
  #   if: github.ref == 'refs/heads/main'
  #   env:
  #     GIT_COMMITTER_NAME: Scaleway Bot
  #     GIT_COMMITTER_EMAIL: github@scaleway.com
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #       with:
  #         fetch-depth: "0"
  #         persist-credentials: false
  #     - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: 17
  #     - run: yarn install
  #     - run: yarn run build
  #     - run: yarn run semantic-release
  #       env:
  #         HUSKY: 0
  #         NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
>>>>>>> fix: ci action
=======
=======
>>>>>>> fix: set a new separate workflow
  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    if: github.ref == 'refs/heads/main'
    env:
      GIT_COMMITTER_NAME: Scaleway Bot
      GIT_COMMITTER_EMAIL: github@scaleway.com
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: "0"
          persist-credentials: false
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17
      - run: yarn install
      - run: yarn run build
      - run: yarn run semantic-release
        env:
          HUSKY: 0
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
>>>>>>> fix: restore other jobs
