name: CI

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: pnpm/action-setup@v2.2.4
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm install
      - run: pnpm tsc --noEmit
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: pnpm/action-setup@v2.2.4
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm install
      - run: pnpm run lint
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ['18']
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: '0'
      - uses: pnpm/action-setup@v2.2.4
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm install
      - run: pnpm run test:unit:coverage
      - uses: codecov/codecov-action@v3.1.1
  accessibility:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: '0'
      - uses: pnpm/action-setup@v2.2.4
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm install
      - run: pnpm run test:a11y
  build:
    strategy:
      matrix:
        node: ['18']
    runs-on: ubuntu-20.04
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: pnpm/action-setup@v2.2.4
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm run build
  chromatic-deployment:
    runs-on: ubuntu-20.04
    env:
      DEPLOYMENT_NAME: 'storybook'
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Export custom variables
        run: |
          SAFE_GITHUB_HEAD_REF_SLUG_URL=$(echo $GITHUB_HEAD_REF_SLUG_URL-$DEPLOYMENT_NAME | rev | cut -c-37 | rev | sed 's/^-//g')
          ([[ $GITHUB_REF == 'refs/heads/main' ]] && echo "BRANCH_SLUG=main" || echo "BRANCH_SLUG=$SAFE_GITHUB_HEAD_REF_SLUG_URL") >> $GITHUB_ENV

      - name: Start deployment
        uses: bobheadxi/deployments@v1.4.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GH_TOKEN }}
          env: ${{ env.BRANCH_SLUG }}
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v2.2.4
      - name: Install dependencies
        run: pnpm install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        id: chromatic
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build:storybook:stats
          onlyChanged: true

      - name: Update deployment
        uses: bobheadxi/deployments@v1.4.0
        with:
          step: finish
          env: ${{ env.BRANCH_SLUG }}
          token: ${{ secrets.GH_TOKEN }}
          auto_inactive: true
          # This will now be automatically handled by github with the auto_inactive
          override: false
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.chromatic.outputs.storybookUrl }}
