name: Deploy

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, console]
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/scaleway-ui
      REMOTE_SSH_SERVER: ssh://root@react.ui.scaleway.com
    steps:
      - uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache-${{ hashFiles('**/yarn.lock') }}
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Export custom variables
        run: |
          SAFE_GITHUB_HEAD_REF_SLUG_URL=$(echo $GITHUB_HEAD_REF_SLUG_URL | rev | cut -c-37 | rev)
          ([[ $REF == 'refs/heads/master' ]] && echo "BRANCH_SLUG=master" || echo "BRANCH_SLUG=$SAFE_GITHUB_HEAD_REF_SLUG_URL") >> $GITHUB_ENV
          ([[ $REF == 'refs/heads/master' ]] && echo "HOST=react.ui.scaleway.com" || echo "HOST=$SAFE_GITHUB_HEAD_REF_SLUG_URL.react.ui.scaleway.com") >> $GITHUB_ENV

      - name: Start deployment
        uses: bobheadxi/deployments@v0.5.2
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.BRANCH_SLUG }}
          ref: ${{ github.head_ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build
        uses: docker/build-push-action@v2
        env:
          IMAGE: ${{ env.IMAGE_NAME }}:${{ env.BRANCH_SLUG }}
        with:
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=local,src=/tmp/.buildx-cache-${{ hashFiles('**/yarn.lock') }}
          cache-to: type=local,dest=/tmp/.buildx-cache-new-${{ hashFiles('**/yarn.lock') }},mode=max

      - name: Set Docker context
        uses: arwynfr/actions-docker-context@98fc92878d0b856c1112c79b8d0f45353206e186
        with:
          docker_host: ${{ env.REMOTE_SSH_SERVER }}
          context_name: ${{ env.BRANCH_SLUG }}
          ssh_cert: ${{ secrets.SSH_CERT }}
          ssh_key: ${{ secrets.SSH_KEY }}
      - name: Deploy docker
        env:
          VERSION: ${{ env.BRANCH_SLUG }}
        # TODO: remove the context rm when we switch back to public runners
        run: |
          docker-compose --context ${VERSION} pull && docker-compose -p ${VERSION} --context ${VERSION} up -d --force-recreate
          docker context rm ${VERSION}

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.5.2
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ env.HOST }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-${{ hashFiles('**/yarn.lock') }}
          mv /tmp/.buildx-cache-new-${{ hashFiles('**/yarn.lock') }} /tmp/.buildx-cache-${{ hashFiles('**/yarn.lock') }}
