
name: Pull Request
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  check-title:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: pnpm/action-setup@v2.4.0
    - name: Use Node.js
      uses: actions/setup-node@v3.8.1
      with:
        node-version: 18
        cache: 'pnpm'
    - run: pnpm install
    - run: echo '${{ github.event.pull_request.title }}' | pnpm commitlint
