name: Pull Request
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  check-title:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: pnpm/action-setup@v3.0.0
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: echo '${{ github.event.pull_request.title }}' | pnpm commitlint
