name: 'size'
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: pnpm/action-setup@v2.4.0
      - uses: andresz1/size-limit-action@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
