name: Design tokens

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * 1-5"

jobs:
  synchronise:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        env:
          LANG: en_US.UTF-8
      - uses: pnpm/action-setup@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - name: Generate json files
        run: pnpm run tokens:update

      - name: Compare & Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: main
          author: Scaleway Design <github@scaleway.com>
          commit-message: 'fix(theme): synchronise design tokens'
          branch: fix/design-tokens-synchronise
          delete-branch: true
          title: 'fix(theme): synchronise design tokens'
          body: |
            Design system tokens update. This MR is created automatically when a change is detected in design tokens.
          team-reviewers: console
          labels:  design system
