name: Design tokens

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * 1-5'

jobs:
  synchronise:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        env:
          LANG: en_US.UTF-8
      - uses: pnpm/action-setup@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - name: Generate json files
        run: pnpm run tokens:update

      - name: Compare & Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: main
          author: Scaleway Design <github@scaleway.com>
          commit-message: 'fix(theme): synchronise design tokens'
          branch: fix/design-tokens-synchronise
          delete-branch: true
          title: 'fix(theme): synchronise design tokens'
          body: |
            Design system tokens update. This MR is created automatically when a change is detected in design tokens.
          team-reviewers: console
          labels: design system
