name: Teardown Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  teardown:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: rg.fr-par.scw.cloud/console-scw/ultraviolet
      STORYBOOK_DEPLOYMENT_NAME: storybook

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Export custom variables
        run: |
          SAFE_STORYBOOK_HEAD_REF=$(echo $GITHUB_HEAD_REF_SLUG_URL-$STORYBOOK_DEPLOYMENT_NAME | rev | cut -c-37 | rev | sed 's/^-//g')
          echo "STORYBOOK_BRANCH_SLUG=$SAFE_STORYBOOK_HEAD_REF" >> $GITHUB_ENV

      - name: Remove storybook deployment
        uses: bobheadxi/deployments@v1.4.0
        with:
          step: delete-env
          token: ${{ secrets.GH_TOKEN }}
          env: ${{ env.STORYBOOK_BRANCH_SLUG }}
