name: Visual

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: pnpm/action-setup@v2.2.3
      - name: Use Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install

      - name: Build Storybook
        run: pnpm run build:storybook-visual

      - name: Lost Pixel
        id: lp
        uses: lost-pixel/lost-pixel@v2.21.0
        env:
          LOST_PIXEL_MODE: update
